data <- read.csv(file.choose(), stringsAsFactors = F)
getwd()
setwd("C:/Users/albo1_000/Documents/R_WorkingDirectory")
getwd()
str(data)
summary(data$Price)
summary(data$SqFt)
summary(data$Offers)
mean(data$Bedrooms)
median(data$Bedrooms)
range(data$Price)
diff(data$Price)
diff(range(data$Price))
IQR(data$Price)
quantile(data$Price, c(0,0.2,0.4,0.6,0.8,1))
boxplot(data$Price, main="Boxplot of House Prices", ylab="Price ($)")
boxplot(data$SqFt, main="Boxplot of SqFt", ylab="SqFt ")
hist(data$Price, main="Spread of Price", xlab="Prices", ylab="Count")
hist(data$Offers, main="Spread of Offers", xlab="Offers", ylab="Count")
var(data$Price)
sd(data$Price)
table(data$Brick)
table(data$Neighborhood)
prop.table(table(data$Neighborhood))*100
prop.table(table(data$Brick))*100
plot(data$SqFt, data$Price, main="Scatter plot between Sqft and Price", xlab="Sqft")
install.packages("gmodels")
library("gmodels")
CrossTable(data$Brick, data$Neighborhood)
